import { ROLES } from "../constants/roles";
import {
  FaChartLine,
  FaUsers,
  FaUserMd,
  FaCalendarAlt,
  FaFileMedical,
  FaPrescription,
  FaDumbbell,
  FaAppleAlt,
  FaChartBar,
  FaRobot,
  FaCrown,
  FaBell,
  FaCog,
  FaFileAlt,
  FaClipboardList,
  FaHistory,
  FaChartPie,
  FaUserTie,
  FaComments,
  FaWalking,
  FaShoppingBag,
  FaHeartbeat,
  FaShoppingBasket,
  FaStore,
  FaMoneyBill,
  FaStethoscope,
} from "react-icons/fa";

import {
  MdManageAccounts,
  MdMedicalServices,
  MdOutlineAssessment,
} from "react-icons/md";
import { GrSchedule } from "react-icons/gr";
// Icon mapping - using component names as strings for config

export const SIDEBAR = [
  // ==================== ADMIN ====================
  {
    name: "Dashboard",
    path: "/admin",
    icon: FaChartLine,
    roles: [ROLES.ADMIN],
    section: "Overview",
  },
  {
    name: "User Management",
    path: "/admin/users",
    icon: MdManageAccounts,
    roles: [ROLES.ADMIN],
    section: "Management",
  },
  {
    name: "Workouts Management",
    path: "/admin/workouts",
    icon: FaDumbbell,
    roles: [ROLES.ADMIN],
    section: "Content",
  },
  {
    name: "Diet Management",
    path: "/admin/diet",
    icon: FaAppleAlt,
    roles: [ROLES.ADMIN],
    section: "Content",
  },
  {
    name: "Product Requests",
    path: "/admin/products",
    icon: FaShoppingBag,
    roles: [ROLES.ADMIN],
    section: "Content",
  },
  {
    name: "Reports",
    path: "/admin/reports",
    icon: FaFileAlt,
    roles: [ROLES.ADMIN],
    section: "Insights",
  },
  {
    name: "Settings",
    path: "/settings",
    icon: FaCog,
    roles: [ROLES.ADMIN],
    section: "Account",
  },

  // ==================== COACH ====================
  {
    name: "Dashboard",
    path: "/coachDashboard",
    icon: FaChartLine,
    roles: [ROLES.COACH],
    section: "Overview",
  },
  {
    name: "Clients",
    path: "/coach/clients",
    icon: MdManageAccounts,
    roles: [ROLES.COACH],
    section: "Clients",
  },
  {
    name: "Members",
    path: "/coach/members",
    icon: FaUsers,
    roles: [ROLES.COACH],
    section: "Clients",
  },
  {
    name: "Workouts",
    path: "/coach/workouts",
    icon: FaDumbbell,
    roles: [ROLES.COACH],
    section: "Training",
  },
  {
    name: "Diet Plans",
    path: "/coach/diet",
    icon: FaAppleAlt,
    roles: [ROLES.COACH],
    section: "Training",
  },
  {
    name: "Sessions",
    path: "/coach/sessions",
    icon: GrSchedule,
    roles: [ROLES.COACH],
    section: "Training",
  },
  {
    name: "Progress",
    path: "/coach/progress",
    icon: FaChartBar,
    roles: [ROLES.COACH],
    section: "Tracking",
  },
  {
    name: "Steps",
    path: "/coach/steps",
    icon: FaWalking,
    roles: [ROLES.COACH],
    section: "Tracking",
  },
  {
    name: "Chat",
    path: "/coach/chat",
    icon: FaComments,
    roles: [ROLES.COACH],
    section: "Communication",
  },
  {
    name: "Notifications",
    path: "/notifications",
    icon: FaBell,
    roles: [ROLES.COACH],
    section: "Communication",
  },
  {
    name: "AI Trainer",
    path: "/coach/ai",
    icon: FaRobot,
    roles: [ROLES.COACH],
    section: "Tools",
  },
  {
    name: "Reports",
    path: "/coach/reports",
    icon: FaFileAlt,
    roles: [ROLES.COACH],
    section: "Tools",
  },
  {
    name: "Products",
    path: "/products",
    icon: FaShoppingBag,
    roles: [ROLES.COACH],
    section: "Tools",
  },
  {
    name: "Plans",
    path: "/coach/plans",
    icon: FaCrown,
    roles: [ROLES.COACH],
    section: "Business",
  },
  {
    name: "Profile",
    path: "/settings",
    icon: FaUserTie,
    roles: [ROLES.COACH],
    section: "Account",
  },

  // ==================== DOCTOR ====================
  {
    name: "Dashboard",
    path: "/doctor",
    icon: FaStethoscope,
    roles: [ROLES.DOCTOR],
    section: "Overview",
  },
  {
    name: "Find Doctors",
    path: "/doctors",
    icon: FaUserMd,
    roles: [ROLES.DOCTOR],
    section: "Overview",
  },
  {
    name: "All Patients",
    path: "/doctor/patients",
    icon: FaUsers,
    roles: [ROLES.DOCTOR],
    section: "Patients",
  },
  {
    name: "Medical History",
    path: "/doctor/medical-history",
    icon: FaFileMedical,
    roles: [ROLES.DOCTOR],
    section: "Patients",
  },
  {
    name: "Appointments",
    path: "/doctor/appointments",
    icon: FaCalendarAlt,
    roles: [ROLES.DOCTOR],
    section: "Clinical Care",
  },
  {
    name: "Prescriptions",
    path: "/doctor/prescriptions",
    icon: FaPrescription,
    roles: [ROLES.DOCTOR],
    section: "Clinical Care",
  },
  {
    name: "Lab Reports",
    path: "/doctor/lab-reports",
    icon: FaFileMedical,
    roles: [ROLES.DOCTOR],
    section: "Clinical Care",
  },
  {
    name: "Progress Tracking",
    path: "/doctor/progress",
    icon: FaChartBar,
    roles: [ROLES.DOCTOR],
    section: "Analytics",
  },
  {
    name: "Risk Assessment",
    path: "/doctor/risk",
    icon: MdOutlineAssessment,
    roles: [ROLES.DOCTOR],
    section: "Analytics",
  },
  {
    name: "Diet Plans",
    path: "/doctor/diet-plans",
    icon: FaAppleAlt,
    roles: [ROLES.DOCTOR],
    section: "Planning",
  },
  {
    name: "Workout Overrides",
    path: "/doctor/workout-adjustments",
    icon: FaDumbbell,
    roles: [ROLES.DOCTOR],
    section: "Planning",
  },
  {
    name: "Chat",
    path: "/doctor/chat",
    icon: FaComments,
    roles: [ROLES.DOCTOR],
    section: "Communication",
  },
  {
    name: "Video Consult",
    path: "/doctor/video",
    icon: FaUserMd,
    roles: [ROLES.DOCTOR],
    section: "Communication",
  },
  {
    name: "Notifications",
    path: "/notifications",
    icon: FaBell,
    roles: [ROLES.DOCTOR],
    section: "Communication",
  },
  {
    name: "Earnings",
    path: "/doctor/earnings",
    icon: FaMoneyBill,
    roles: [ROLES.DOCTOR],
    section: "Business",
  },
  {
    name: "Subscriptions",
    path: "/doctor/subscriptions",
    icon: FaCrown,
    roles: [ROLES.DOCTOR],
    section: "Business",
  },
  {
    name: "Profile Settings",
    path: "/settings",
    icon: FaCog,
    roles: [ROLES.DOCTOR],
    section: "Account",
  },

  // ==================== USER ====================
  {
    name: "Dashboard",
    path: "/dashboard",
    icon: FaChartLine,
    roles: [ROLES.USER],
    section: "Overview",
  },
  {
    name: "Find Doctors",
    path: "/doctors",
    icon: FaUserMd,
    roles: [ROLES.USER],
    section: "Overview",
  },
  {
    name: "My Orders",
    path: "/orders",
    icon: FaClipboardList,
    roles: [ROLES.USER],
    section: "Marketplace",
  },
  {
    name: "Cart",
    path: "/cart",
    icon: FaShoppingBasket,
    roles: [ROLES.USER],
    section: "Marketplace",
  },
  {
    name: "Add Workouts",
    path: "/workouts",
    icon: FaDumbbell,
    roles: [ROLES.USER],
    section: "Workouts",
  },
  {
    name: "Workout Analytics",
    path: "/workout-analytics",
    icon: FaChartPie,
    roles: [ROLES.USER],
    section: "Workouts",
  },
  {
    name: "Workout History",
    path: "/workout-history",
    icon: FaHistory,
    roles: [ROLES.USER],
    section: "Workouts",
  },
  {
    name: "Add-Diet",
    path: "/add-meal",
    icon: FaAppleAlt,
    roles: [ROLES.USER],
    section: "Nutrition",
  },
  {
    name: "Chat",
    path: "/chat",
    icon: FaComments,
    roles: [ROLES.USER],
    section: "Communication",
  },
  {
    name: "Notifications",
    path: "/notifications",
    icon: FaBell,
    roles: [ROLES.USER],
    section: "Communication",
  },
  {
    name: "Progress",
    path: "/progress",
    icon: FaChartBar,
    roles: [ROLES.USER],
    section: "Tracking",
  },
  {
    name: "Steps",
    path: "/steps",
    icon: FaWalking,
    roles: [ROLES.USER],
    section: "Tracking",
  },
  {
    name: "AI Trainer",
    path: "/ai",
    icon: FaRobot,
    roles: [ROLES.USER],
    section: "Tools",
  },
  {
    name: "Products",
    path: "/products",
    icon: FaShoppingBag,
    roles: [ROLES.USER],
    section: "Tools",
  },
  {
    name: "Health Tips",
    path: "/health-tips",
    icon: FaHeartbeat,
    roles: [ROLES.USER],
    section: "Wellness",
  },
  {
    name: "Grocery",
    path: "/grocery",
    icon: FaStore,
    roles: [ROLES.USER],
    section: "Wellness",
  },
  {
    name: "Plans",
    path: "/plans",
    icon: FaCrown,
    roles: [ROLES.USER],
    section: "Membership",
  },
  {
    name: "Settings",
    path: "/settings",
    icon: FaCog,
    roles: [ROLES.USER],
    section: "Account",
  },

  // ==================== SELLER ====================
  {
    name: "Dashboard",
    path: "/seller",
    icon: FaStore,
    roles: [ROLES.SELLER],
    section: "Store",
  },
  {
    name: "My Products",
    path: "/seller/products",
    icon: FaShoppingBag,
    roles: [ROLES.SELLER],
    section: "Store",
  },
  {
    name: "Orders",
    path: "/seller/orders",
    icon: FaClipboardList,
    roles: [ROLES.SELLER],
    section: "Store",
  },

  // ==================== AFFILIATE ====================
  {
    name: "Dashboard",
    path: "/affiliate",
    icon: FaChartLine,
    roles: [ROLES.AFFILIATE],
    section: "Affiliate",
  },
  {
    name: "Earnings",
    path: "/affiliate/earnings",
    icon: FaMoneyBill,
    roles: [ROLES.AFFILIATE],
    section: "Affiliate",
  },
  {
    name: "Referrals",
    path: "/affiliate/referrals",
    icon: FaUsers,
    roles: [ROLES.AFFILIATE],
    section: "Affiliate",
  },
];
