export const copyWorkoutPlan = async (workout) => {
  const text = `Workout: ${workout.name}\n` +
    `Duration: ${workout.duration} minutes\n` +
    `Exercises:\n` +
    (workout.exercises || []).map(ex => `- ${ex.name}: ${ex.sets || 3} sets x ${ex.reps || 12} reps`).join('\n') +
    `\nGenerated by FitTrackX`;
  
  return await copyToClipboard(text);
};

export const copyDietPlan = async (mealPlan) => {
  const text = `Diet Plan: ${mealPlan.name}\n` +
    `Calories: ${mealPlan.calories}\n` +
    `Meals:\n` +
    (mealPlan.meals || []).map(m => `- ${m.name}: ${m.description}`).join('\n') +
    `\nFrom FitTrackX`;
  
  return await copyToClipboard(text);
};

// Generic copy function
export const copyToClipboard = async (text) => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error("Failed to copy:", err);
    return false;
  }
};
